### ISSUE TITLE
Understanding: How to add additional tables

### ISSUE THREAD

**Issue by addorange** [heimrichhannot/contao-filecredits#3]
Hi,

a very useful extension, but I'm struggling with the option to respect files used within my own extension. Using a table "tl_simple_catalog" I do add also images to each item. These items are listed on the frontend within a list module. Is there any chance to put them into the file credits array, too?

As a quick and dirty workaround for now I just modified your extension to list all files with a copyright. 

Cheers,

Chrs

**Comment by fatcrobat** [comment]
Here an example:

config.php of in your modules/config folder

```
$GLOBALS['TL_FILECREDIT_MODELS']['tl_simple_catalog'] = 'items';
```

The key must be the table name "tl_simple_catalog" and the value is the module reader auto_item name.
