### ISSUE TITLE
Copyright input in filemanagement behaving strangely 

### ISSUE THREAD

**Issue by manjarco** [heimrichhannot/contao-filecredits#5]
Running contao 3.5.27, filecredits 2.1.15 I get a variation of this every time I try to type a copyright:

<img width="326" alt="bildschirmfoto 2017-06-08 um 16 18 28" src="https://user-images.githubusercontent.com/274524/27028600-89f6faa0-4f65-11e7-8bec-04f8e01c5906.png">

I tried deinstalling filecredits with all its dependencies and deleting the db-tables, but a fresh install brings no improvement.

**Comment by fatcrobat** [comment]
@manjarco Deployed 2.1.16, that should fix this issue.
