### ISSUE TITLE
Möglichkeit, nur Dateien mit Copyright-Informationen zu listen

### ISSUE THREAD

**Issue by arboc** [heimrichhannot/contao-filecredits#8]
Wir benötigen eine Möglichkeit, dass im Frontend nur die Dateien gelistet werden, bei denen eine Copyright-Information hinterlegt ist. Am besten wäre hier eine Checkbox im Frontendmodule um diesen Filter zu aktivieren / deaktivieren.

Hintergrund:  
Wir haben Websites, bei denen einige (wenige) Bilder gekauft sind und diese im Impressum erscheinen sollen. Und eine Vielzahl von Bildern, die vom Betreiber der Website kommen. Diese sollen aber nicht explizit genannt werden.

**Comment by fatcrobat** [comment]
@arboc Das sollte das normale Verhalten des Moduls doch bereits abdecken. Es werden nur Bilder vom Crawler erfasst, die auch über ein `copyright` verfügen.
