### ISSUE TITLE
Manuell hinzugefügte Seitenangaben gehen bei manuellen Snyc verloren

### ISSUE THREAD

**Issue by kaeptn2lvl** [heimrichhannot/contao-filecredits#9]
Der Betreff drückt es ziemlich genau aus, was passiert...
(contao 4.4 )

**Comment by koertho** [comment]
Sollte seit 3.0.2 oder 2.2.6 eigentlich behoben sein. Welche Version setzt du ein?

**Comment by kaeptn2lvl** [comment]
Version 3.1.4
(17.4.2018, 08:52:21)

**Comment by K0NZ1** [comment]
Hallo, kannst du uns vielleicht einen dump von deiner tl_filecredit und tl_filecredit_page Tabelle zur Verfügung stellen, damit wir den Fehler nachvollziehen können? Wir können den Fehler leider nicht reproduzieren.

**Comment by kaeptn2lvl** [comment]
Folgender Fall: Filecredit zeigt mir alle Bilder und deren Seitenangaben aus dem Sync. Ich füge einem der Bilder eine manuelle Seitenangabe hinzu. Alles paletti, bis ich wieder auf sync drücke, dann verschwindet die manuelle Seitenangabe.

Wie und wem kann ich den Dump schicken? Ihr bekämet zwei, einen vorher und nacher dump

**Comment by K0NZ1** [comment]
@kaeptn2lvl Ich habe soeben ein Update eingespielt. (3.1.5) Damit sollte der Fehler behoben sein.
